In [56]:
import pandas as pd

In [57]:
d = {
     'Python': [12, 20, 19, 20], 
     'C++'   : [20, 20, 18, 16], 
     'Java'  : [18, 13, 12, 9] 
}

df = pd.DataFrame(d)
df

   Python  C++  Java
0      12   20    18
1      20   20    13
2      19   18    12
3      20   16     9

In [58]:
name = ['Ali', 'Farshid', 'Taha', 'Mahsa']

df = pd.DataFrame(data=d, index=name)
df

         Python  C++  Java
Ali          12   20    18
Farshid      20   20    13
Taha         19   18    12
Mahsa        20   16     9

In [59]:
df.columns

Index(['Python', 'C++', 'Java'], dtype='object')

In [60]:
df.index

Index(['Ali', 'Farshid', 'Taha', 'Mahsa'], dtype='object')

In [61]:
df[['Python', 'Java']]

         Python  Java
Ali          12    18
Farshid      20    13
Taha         19    12
Mahsa        20     9

In [62]:
df[:2]

         Python  C++  Java
Ali          12   20    18
Farshid      20   20    13

In [63]:
df.loc['Taha']

Python    19
C++       18
Java      12
Name: Taha, dtype: int64

In [64]:
df.loc['Taha', ['Python','Java']]

Python    19
Java      12
Name: Taha, dtype: int64

In [65]:
df.iloc[2, [0, 2]]

Python    19
Java      12
Name: Taha, dtype: int64

In [66]:
df.iloc[:, [True, False, True]]

         Python  Java
Ali          12    18
Farshid      20    13
Taha         19    12
Mahsa        20     9

In [67]:
df.mean()

Python    17.75
C++       18.50
Java      13.00
dtype: float64

In [68]:
df.describe()

         Python        C++       Java
count   4.00000   4.000000   4.000000
mean   17.75000  18.500000  13.000000
std     3.86221   1.914854   3.741657
min    12.00000  16.000000   9.000000
25%    17.25000  17.500000  11.250000
50%    19.50000  19.000000  12.500000
75%    20.00000  20.000000  14.250000
max    20.00000  20.000000  18.000000

In [69]:
df.drop(['Mahsa'])

         Python  C++  Java
Ali          12   20    18
Farshid      20   20    13
Taha         19   18    12

In [70]:
df.T

        Ali  Farshid  Taha  Mahsa
Python   12       20    19     20
C++      20       20    18     16
Java     18       13    12      9

In [71]:
df.apply(lambda x: x+2)

         Python  C++  Java
Ali          14   22    20
Farshid      22   22    15
Taha         21   20    14
Mahsa        22   18    11

In [72]:
#

In [73]:
df.to_csv('test.csv', index=False)

In [74]:
df = pd.read_csv('test.csv')

In [75]:
#

In [76]:
import numpy as np
from numpy import nan as NA

In [77]:
d = [[15, 12, 19], [15, 12, 19], [13, 1, 6], [18, NA, 7], [18, NA, 16], [14, NA, NA], [12, NA, NA]]
df = pd.DataFrame(d)
df

    0     1     2
0  15  12.0  19.0
1  15  12.0  19.0
2  13   1.0   6.0
3  18   NaN   7.0
4  18   NaN  16.0
5  14   NaN   NaN
6  12   NaN   NaN

In [78]:
df = df.drop_duplicates()
df

    0     1     2
0  15  12.0  19.0
2  13   1.0   6.0
3  18   NaN   7.0
4  18   NaN  16.0
5  14   NaN   NaN
6  12   NaN   NaN

In [79]:
cleaned = df.dropna()
cleaned

    0     1     2
0  15  12.0  19.0
2  13   1.0   6.0

In [80]:
frame = df.fillna(0)
frame

    0     1     2
0  15  12.0  19.0
2  13   1.0   6.0
3  18   0.0   7.0
4  18   0.0  16.0
5  14   0.0   0.0
6  12   0.0   0.0

In [81]:
#

In [82]:
df1 = pd.DataFrame({'Name': ['ali', 'taha', 'mahsa'], 
                    'C++': [18, 12, 17]})
df1

    Name  C++
0    ali   18
1   taha   12
2  mahsa   17

In [83]:
df2 = pd.DataFrame({'Name': ['ali', 'taha', 'farshid'], 
                    'Python': [13, 14, 16]})
df2

      Name  Python
0      ali      13
1     taha      14
2  farshid      16

In [84]:
pd.concat([df1, df2])

      Name   C++  Python
0      ali  18.0     NaN
1     taha  12.0     NaN
2    mahsa  17.0     NaN
0      ali   NaN    13.0
1     taha   NaN    14.0
2  farshid   NaN    16.0

In [85]:
#

In [86]:
df1.merge(df2)

   Name  C++  Python
0   ali   18      13
1  taha   12      14

In [87]:
df1.merge(df2, how='outer')

      Name   C++  Python
0      ali  18.0    13.0
1  farshid   NaN    16.0
2    mahsa  17.0     NaN
3     taha  12.0    14.0

In [88]:
df1.merge(df2, how='left')

    Name  C++  Python
0    ali   18    13.0
1   taha   12    14.0
2  mahsa   17     NaN

In [89]:
df1.merge(df2, how='right')

      Name   C++  Python
0      ali  18.0      13
1     taha  12.0      14
2  farshid   NaN      16

In [90]:
#

In [91]:
df1 = pd.DataFrame([[19, 12], [13, 18], [5, 16]], 
                   index=['ali', 'mahsa', 'taha'], 
                   columns=['C++', 'Python'])
df1

       C++  Python
ali     19      12
mahsa   13      18
taha     5      16

In [92]:
df2 = pd.DataFrame([[17, 12], [19, 20], [11, 6], [13, 18]], 
                   index=['farid', 'farshid', 'mahsa', 'taha'], 
                   columns=['Java', 'PHP'])
df2

         Java  PHP
farid      17   12
farshid    19   20
mahsa      11    6
taha       13   18

In [93]:
df1.join(df2)

       C++  Python  Java   PHP
ali     19      12   NaN   NaN
mahsa   13      18  11.0   6.0
taha     5      16  13.0  18.0

In [94]:
df2.join(df1)

         Java  PHP   C++  Python
farid      17   12   NaN     NaN
farshid    19   20   NaN     NaN
mahsa      11    6  13.0    18.0
taha       13   18   5.0    16.0

In [95]:
df2.join(df1, how='outer')

         Java   PHP   C++  Python
ali       NaN   NaN  19.0    12.0
farid    17.0  12.0   NaN     NaN
farshid  19.0  20.0   NaN     NaN
mahsa    11.0   6.0  13.0    18.0
taha     13.0  18.0   5.0    16.0

In [96]:
#

In [97]:
df = pd.DataFrame({'Name': ['farid', 'farid', 'omid', 'omid'],
                   'score': [18, 17., 12, 20]})
df

    Name  score
0  farid   18.0
1  farid   17.0
2   omid   12.0
3   omid   20.0

In [98]:
df.groupby(['Name']).mean()

       score
Name
farid   17.5
omid    16.0

In [99]:
df.groupby(['Name']).max()

       score
Name
farid   18.0
omid    20.0

In [100]:
df.groupby("Name").apply(lambda x: x+1)

         score
Name
farid 0   19.0
      1   18.0
omid  2   13.0
      3   21.0

In [101]:
df = pd.DataFrame(
        [
          ("b", "b1", 12),
          ("b", "b2", 14),
          ("b", "b2", 20),
          ("m", "m1", 13),
          ("m", "m2", 14),
          ("m", "m1", 16),
       ],
       columns=("A", "B", "C"),
)

df

   A   B   C
0  b  b1  12
1  b  b2  14
2  b  b2  20
3  m  m1  13
4  m  m2  14
5  m  m1  16

In [102]:
df.groupby(["A", "B"]).max()

       C
A B
b b1  12
  b2  20
m m1  16
  m2  14

In [104]:


pd.DataFrame({'column1': (1, 2, 3), 'column2': (4, 5, 6)})

   column1  column2
0        1        4
1        2        5
2        3        6